config/routes.rb
Rails.application.routes.draw do
  resources :flats
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  # GET /flats
  def index
    @flats = Flat.all
  end

  # GET /flats/1
  def show
  end

  # GET /flats/new
  def new
    @flat = Flat.new
  end

  # GET /flats/1/edit
  def edit
  end

  # POST /flats
  def create
    @flat = Flat.new(flat_params)

    if @flat.save
      redirect_to @flat, notice: 'Flat was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /flats/1
  def update
    if @flat.update(flat_params)
      redirect_to @flat, notice: 'Flat was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /flats/1
  def destroy
    @flat.destroy
    redirect_to flats_url, notice: 'Flat was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flat
      @flat = Flat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def flat_params
      params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(@flat) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/flats/edit.html.erb
<h1>Editing Flat</h1>

<%= render 'form', flat: @flat %>

<%= link_to 'Show', @flat %> |
<%= link_to 'Back', flats_path %>

app/views/flats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All our flats</h1>
<div class="container">
  <div class="row">
    <% @flats.each do |flat| %>
      <div class="col-md-3 gap-2 mb-3">
        <div class="card shadow-sm h-100">
          <div class="card-body bg-light">
            <h5 class="card-title"><%= flat.name %></h5>
            <p class="card-text"><%= flat.address %></p>
            <div class="d-flex gap-3">
              <i class="fa-solid fa-user-group">  <%= flat.number_of_guests %></i>
              <i class="fa-solid fa-euro-sign">  <%= flat.price_per_night %></i>
            </div>
          </div>
        <div class="card-footer bg-white">
          <%= link_to 'Show', flat_path(flat), class: 'text-decoration-none' %>
        </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<h1>New Flat</h1>

<%= render 'form', flat: @flat %>

<%= link_to 'Back', flats_path, class: 'btn btn-primary mt-3' %>

app/views/flats/show.html.erb
<div class="banner" style="background-image: url('https://source.unsplash.com/random/?villa')">
</div>

<div class="container">
  <div class="card bg-light my-3">
    <div class="card-body">
      <h2 class="card-title"><%= @flat.name %></h2>
      <p><%= @flat.address %></p>
    </div>
  </div>

  <div class="card bg-light my-3">
    <div class="card-body">
      <h3 class="card-title">A bit more about this flat</h3>
      <p><%= @flat.description %></p>
    </div>
  </div>

  <div class="card bg-light my-3">
    <div class="card-body">
      <h3 class="card-title">Details</h3>
      <div class="d-flex gap-3">
        <i class="fa-solid fa-user-group">  <%= @flat.number_of_guests %></i>
        <i class="fa-solid fa-euro-sign">  <%= @flat.price_per_night %></i>
      </div>
    </div>
  </div>

  <%= link_to 'Edit', edit_flat_path(@flat) %> |
  <%= link_to 'Back', flats_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/66112e6f8b.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="/flats">
          <%= image_tag 'Airbnb-logo.png', class: 'd-inline-block align-text-top', height: '40px' %>
          Victor's Airbnb
        </a>
        <%= link_to "Add flat", new_flat_path, class: "btn btn-primary" %>
        <%# <a href="#" class="btn btn-primary">Add flat</a> %>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>